### ISSUE TITLE
Add BootsFaces autoconfiguration

### ISSUE THREAD

**Issue by stephanrauh** [persapiens/jsf-spring-boot-starter#74]
Hi Marcelo,

since you've left an announcement to your project on my blog, I'd like to encourage you to add autoconfigurations for BootsFaces and AngularFaces :). BootsFaces, in particular, has become a major player in the JSF world recently. Currently (May 2016), we see more than 2000 downloads per months, and the figures are rising quickly. So it may be worth the pain!

Best regards,
Stephan

**Comment by persapiens** [comment]
I'll be a pleasure Stephan.

Could you:

* give some advice about BootsFaces and AngularFaces **compatibility with current versions** of PrimeFaces, OmniFaces, Mojarra, MyFaces, Tomcat, Jetty and Undertow?

* point some documentation about **specific BootsFaces and AngularFaces context-param**?

* explain any **important configuration tip** to be known?

Sincerely,
Marcelo

**Comment by persapiens** [comment]
Dear @stephanrauh ,

I've implemented autoconfigurations for BootsFaces and AngularFaces at master branch. 

I've tested these libraries at [JSF Spring Boot Starter Example](https://github.com/persapiens/jsf-spring-boot-starter-example), but they broke helloWorld page a little. I could not see any bootsfaces component also.

Could you give me some help? To make tests, you could:

* download both [JSF Spring Boot Starter](https://github.com/persapiens/jsf-spring-boot-starter) and [JSF Spring Boot Starter Example](https://github.com/persapiens/jsf-spring-boot-starter-example);

* change jsf-spring-boot-starter.version to 1.5.2-SNAPSHOT at example pom.xml

* change src/main/resources/META-INF/resources/helloWorld.xhtml to test butterfaces and angularfaces components

Current example setup uses mojarra 2.2.13, primefaces 6.0, primefaces-extensions 6.0.0, omnifaces 1.13, spring boot 1.3.5 and tomcat 8.0.33.

I look forward you answer.

**Comment by persapiens** [comment]
Hi again @stephanrauh 

I run the [JSF Spring Boot Starter Example](https://github.com/persapiens/jsf-spring-boot-starter-example) again with MyFaces instead of Mojarra using jsf-myfaces-spring-boot-starter.

Now, I see ButterFaces components, but helloWorld page seems different.
For example, If I don't include any buttefaces components, text font size are shorter.

Current example setup uses **bootsfaces 0.8.6, angularFaces-core 2.1.11, myfaces-bundle 2.2.10**, primefaces 6.0, primefaces-extensions 6.0.0, omnifaces 1.13, spring boot 1.3.5 and tomcat 8.0.33.

I look forward you answer.

**Comment by persapiens** [comment]
I've migrated two BootsFaces projects from forked [BootsFaces Examples](https://github.com/persapiens/BootsFaces-Examples): PrimeFacesLayoutJSBS and ResponsiveDesignJSBS.

Using MyFaces I think they are ok. Both projects use PrimeFaces also.

If we don't solve issues between BootsFaces/AngularFaces and jsf-spring-boot-starter (1- they don't work with Mojarra, 2- [JSF Spring Boot Starter Example](https://github.com/persapiens/jsf-springboot-starter-example) incompatibility), I think I'll create three new starters specific to BootsFaces/AngularFaces (using MyFaces with Tomcat, Jetty or Undertow) instead of adding it to existing ones.

**Comment by stephanrauh** [comment]
Please excuse my silence. We're currently preparing the 0.9 release of BootsFaces, and that's always a very busy time!

In theory, Mojarra 2.2.13 should work with Spring Boot (see http://www.beyondjava.net/blog/updating-to-mojarra-2-2-11-may-break-your-spring-boot-application/). However, I've been talking with the core JSF developers recently, and they seem to be serious about integrating JSF with the rest of JavaEE. In particular, there's a strategy that makes CDI a required library in the near future. I guess in 2.3 it's mostly optional, but even so, @ManagedBean already is deprecated. I don't know whether Spring is able to build a bridge between the Spring container and the CDI container.

If AngularFaces troubles you - don't bother. It's a nice project, but it's far from being popular, and it's incompatible with Angular2. One day or another I'll have to create a new version running on Angular2, but until then, AngularFaces is sort of deprecated. On the other hand, I don't think AngularFaces causes problems.

I'll try to come back and have a look at your project after releasing the new version of BootsFaces.

Best regards
Stephan

**Comment by persapiens** [comment]
I've tested jsf-spring-boot-starter with Mojarra 2.2.10 and it works with BootsFaces. However, I've already implemented JSF annotation scanning because of issue #66 . Do you know which BootsFaces classes are not loaded for example?

I see you point about a bridge between Spring container and CDI container. I usually use only Spring container with SpringBeanFacesELResolver, but Jsf Spring Boot Starter convert classes annotated with JSF and CDI scopes  like @ViewScoped, @SessionScoped, @ApplicationScoped to equivalent Spring Scope.

I've migrated more two BootsFaces projects from forked BootsFaces Examples: AJAXJSBS and AddingPrimeFaces5.3JSBS. Four projects works well with MyFaces.

I think I could wait 0.9 release of BootsFaces because of [PrimeFaces 6.0 compatibility](https://github.com/TheCoder4eu/BootsFaces-OSP/issues/411) issue before releasing next jsf-spring-boot-starter.

If AngularFaces really does not cause problems, we could use it.

Sincerely,
Marcelo

**Comment by stephanrauh** [comment]
Yes, it's high time to update the `SpringBeanFacesELResolver`. I don't think it's difficult to add the view scope, but for some reason nobody but me seems to miss it. I also suspect that sooner or later the JSF team will start to use an internal API of CDI. When that happens, it's become very difficult to make Spring compatible with JSF.

BTW, the PF 6.0 bug seems to be a nasty one. We'll probably tackle it after releasing 0.9.0.

**Comment by persapiens** [comment]
I've just improved the way jsf-spring-boot-starter scans classes and now BootsFaces and Mojarra work at BootsFacesExamples. Thanks for help :)

I've tested BootsFaces at [Jsf Spring Boot Starter Example](https://github.com/persapiens/jsf-spring-boot-starter-example) again and I have the following issues now at helloWorld.xhtml: (I tested both primefaces 5.3 and 6.0, mojarra and myfaces with the same result.)
- BootsFaces: text font size smaller.
- ArgularFaces: break p:panelGrid for input nickname.

More, imagine I'll create new jsf spring boot starters for BootsFaces. Would you:
- include AngularFaces ?
- include PrimeFaces? Version 5.3 or 6.0?
- wait BootsFaces 0.9 release?

I look forward you answer.

**Comment by stephanrauh** [comment]
Like I've said, if AngularFaces breaks PrimeFaces compatibility, drop it. It's a pity, but it's not the end of the world.

PrimeFaces 6.0: currently there's an incompatibility to PF 6.0. So I'd opt for 5.3 until we've fixed the bug. I'm afraid it's a difficult bug, so we won't solve it before BF 0.9.1.

BootsFaces 0.9.0: well, we're going to release the version this weekend, unless there's a last-minute change of plan. In the meantime, you can experiment with our snapshot version (see https://github.com/TheCoder4eu/BootsFaces-OSP/issues/369).

**Comment by persapiens** [comment]
I've just pushed six new starters for BootsFaces, using all combinations between servlet containers (tomcat, jetty, undertow) and jsf implementation (mojarra, myfaces). I've converted six projects from forked BootsFacesExamples to use all of them.

All bootsfaces starters include bootsfaces **0.8.6**, omnifaces **1.13**, primefaces **5.3** and angularfaces **2.1.11**.

I'm going to experiment BootsFaces 0.9.0 snapshot with BootsFacesExamples this week.

I'll release jsf-spring-boot-starter next wednesday. If 0.9.0 is available, I'll use it. Otherwise, I'll release again when it is available.

**Comment by persapiens** [comment]
@stephanrauh , I've tested BootsFaces 0.9.0 snapshot with no side effect with primefaces. This version seems better than 0.8.6.

I saw PrimeFaces 6.0 bug was fixed by Omnifaces 2.4. Do you think PF 6.0 is compatible with BootsFaces now?

**Comment by stephanrauh** [comment]
Yes, I believe PF 6.0 to be compatible to BootsFaces. The problem was caused by a third-party library. The OmniFaces bugfix is really clever, but it doesn't solve the supposed incompatibility to BootsFaces. That was caused by accessing a JavaScript file that was removed between PF 5.3 and 6.0.

**Comment by persapiens** [comment]
Hum, I think we don't have any issues now. 

I've discovered that there is no problem with AngularFaces. [It addLabels and addMessages by default](https://www.angularfaces.net/version2.1/tutorial/step_01/index.jsf). It is not an error, it is a feature :)

I'll release BootsFaces starters using PF 6.0 next thursday. These starters use AngularFaces also. I'll release again when 0.9.0 is available.

I think we could close this issue.

**Comment by stephanrauh** [comment]
We've just released BootsFaces 0.9.0.

**Comment by persapiens** [comment]
Great news @stephanrauh 

Let's use it right now.

Congratulations.
